# Generated by Django 5.0.14 on 2025-12-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
        ('tests', '0003_test_is_bank_testsession_set_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['bank_order', 'order', 'created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='bank_order',
            field=models.IntegerField(default=0, help_text='Global index in the unified question bank'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within a test if not in a bank'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['bank_order'], name='questions_bank_or_175ee3_idx'),
        ),
    ]
