# Generated by Django 5.0.14 on 2025-12-16 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testsession',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tests.test'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['user', '-started_at'], name='test_sessio_user_id_bbb317_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['test', '-started_at'], name='test_sessio_test_id_805455_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['status'], name='test_sessio_status_baade3_idx'),
        ),
    ]
