# Generated by Django 5.0.14 on 2025-12-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_bank',
            field=models.BooleanField(default=False, help_text='Is this a unified question bank?'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='set_number',
            field=models.IntegerField(default=1, help_text='The partition number of the bank'),
        ),
    ]
